server:
    port: 8081

spring:
    application:
        version: 1.0.0
        organization:
            name: next-spring-kart
        name: user-service

    datasource:
        url: jdbc:postgresql://${PGHOST:localhost}:5432/${PGDATABASE:user_db}?sslmode=require
        username: ${PGUSER:postgres}
        password: ${PGPASSWORD:password}
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                transaction:
                    jta:
                        platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

    flyway:
        enabled: true
        locations: classpath:db/migrations
        baseline-on-migrate: true
        placeholders:
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
            ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME}
            ADMIN_LAST_NAME: ${ADMIN_LAST_NAME}

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

jwt:
    secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345}
    expiration: ${JWT_EXPIRATION:3600000} # Default 1 hour

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    level:
        org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

management:
    endpoint:
        health:
            show-details: always
