spring:
    config:
        activate:
            on-profile: production
    datasource:
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            idle-timeout: 600000
            max-lifetime: 1800000
    jpa:
        properties:
            hibernate:
                format_sql: false

logging:
    level:
        com.ecommerce.userservice: INFO
        org.springframework.security: WARN
    file:
        name: logs/user-service.log
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus