spring:
    config:
        activate:
            on-profile: dev
    datasource:
        hikari:
            maximum-pool-size: 5
    jpa:
        show-sql: true

logging:
    level:
        com.nextspringkart: DEBUG
        org.springframework: INFO
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE


gateway:
    url: http://localhost:8080